name: Get azdo wi link step

on:
  pull_request:
    branches: [ master ]
    
jobs:
  alert:
    runs-on: ubuntu-latest
    steps:
      - uses: solidify/github-action-azdo-link@master
        with:
          organization: 'SolidifyDemo'
          projectName: 'Azure DevOps-GitHub Demo'
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
    

